### ISSUE TITLE
ArrayOutOfBoundsException in the sample

### ISSUE THREAD

**Issue by vipulasri** [alexjlockwood/kyrie#1]
Below error is coming in two samples:
1. Polgon
2. Progress Bar

Stacktrace: 

`Process: com.example.kyrie, PID: 26838
                                                                   java.lang.ArrayIndexOutOfBoundsException: length=300; index=300
                                                                       at com.github.alexjlockwood.kyrie.PathKeyframeSet.interpolateInRange(PathKeyframeSet.java:83)
                                                                       at com.github.alexjlockwood.kyrie.PathKeyframeSet.getAnimatedValue(PathKeyframeSet.java:69)
                                                                       at com.github.alexjlockwood.kyrie.PathKeyframeSet.getAnimatedValue(PathKeyframeSet.java:21)
                                                                       at com.github.alexjlockwood.kyrie.Animation.getAnimatedValue(Animation.java:390)
                                                                       at com.github.alexjlockwood.kyrie.Property.getAnimatedValue(Property.java:176)
                                                                       at com.github.alexjlockwood.kyrie.BaseNode$BaseLayer.draw(BaseNode.java:117)
                                                                       at com.github.alexjlockwood.kyrie.KyrieDrawable.draw(KyrieDrawable.java:297)
                                                                       at android.widget.ImageView.onDraw(ImageView.java:1299)
                                                                       at android.view.View.draw(View.java:17083)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16065)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:16028)
                                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
                                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
                                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2808)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2616)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)`

**Comment by alexjlockwood** [comment]
Weird. Can you provide some details about the device you were using at the time?

**Comment by vipulasri** [comment]
Device: Moto G4 Plus
OS: Android 7.0

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7822179/36463327-46f1bae0-16ef-11e8-8b33-c2aacce00ae3.gif)

**Comment by alexjlockwood** [comment]
Thanks for reporting! I'm guessing this has something to do with my Path#approximate() backport for pre-O devices: https://github.com/alexjlockwood/kyrie/blob/master/library/src/main/java/com/github/alexjlockwood/kyrie/PathKeyframeSet.java#L108-L164

Will take a look...

**Comment by alexjlockwood** [comment]
This should be fixed now. Let me know if you have any trouble!

p.s. I ended up finding a rare bug in the support library due to this bug report so thanks. :)

**Comment by LouisCAD** [comment]
@alexjlockwood What is the big you found in the support library? Any b.android.com link?

**Comment by alexjlockwood** [comment]
https://issuetracker.google.com/issues/74051105
